# Generated by Django 5.0.6 on 2024-05-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ou_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='workin_day',
            new_name='working_day',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='workin_time',
            new_name='working_time',
        ),
    ]
